version: '3.8'

services:
  authentication:
    build:
      context: .
      dockerfile: docker/Dockerfile.nest.base
      target: ${NODE_ENV:-production}
      args:
        SERVICE_NAME: authentication
      no_cache: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=auth
      - PROTO_PATH=/app/proto/stat-auto-complete.proto

  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.nest.base
      target: ${NODE_ENV:-production}
      args:
        SERVICE_NAME: gateway
      no_cache: true
    ports:
      - "3001:3000"
    depends_on:
      - authentication
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: ${NODE_ENV:-production}
      no_cache: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    depends_on:
      - gateway
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  stables:
    build:
      context: .
      dockerfile: docker/Dockerfile.nest.base
      target: ${NODE_ENV:-production}
      args:
        SERVICE_NAME: stables
      no_cache: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3003:3000"
    depends_on:
      - authentication
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  courses:
    build:
      context: .
      dockerfile: docker/Dockerfile.nest.base
      target: ${NODE_ENV:-production}
      args:
        SERVICE_NAME: courses
      no_cache: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3004:3000"
    depends_on:
      - authentication
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  pilotes:
    build:
      context: .
      dockerfile: docker/Dockerfile.nest.base
      target: ${NODE_ENV:-production}
      args:
        SERVICE_NAME: pilotes
      no_cache: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3005:3000"
    depends_on:
      - authentication
    environment:
      - NODE_ENV=${NODE_ENV:-production}

networks:
  default:
    driver: bridge
