# docker/Dockerfile.base

FROM node:20-alpine AS base

RUN apk add --no-cache bash

# Activer pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages

RUN pnpm install --frozen-lockfile
